image: node:18-alpine

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
    - rm -rf public
    - mv dist/spa public
  artifacts:
    paths:
      - public
  only:
    - main # หรือ master ตามชื่อ branch หลัก
