/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/products/': RouteRecordInfo<
      '/products/',
      '/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/purchase-orders/': RouteRecordInfo<
      '/purchase-orders/',
      '/purchase-orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/': RouteRecordInfo<
      '/reports/',
      '/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stock/adjust': RouteRecordInfo<
      '/stock/adjust',
      '/stock/adjust',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stock/alerts': RouteRecordInfo<
      '/stock/alerts',
      '/stock/alerts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stock/in': RouteRecordInfo<
      '/stock/in',
      '/stock/in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stock/movements': RouteRecordInfo<
      '/stock/movements',
      '/stock/movements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stock/out': RouteRecordInfo<
      '/stock/out',
      '/stock/out',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/suppliers/': RouteRecordInfo<
      '/suppliers/',
      '/suppliers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/': RouteRecordInfo<
      '/users/',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vehicles/compatibility': RouteRecordInfo<
      '/vehicles/compatibility',
      '/vehicles/compatibility',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/products/index.vue': {
      routes:
        | '/products/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/purchase-orders/index.vue': {
      routes:
        | '/purchase-orders/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reports/index.vue': {
      routes:
        | '/reports/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/stock/adjust.vue': {
      routes:
        | '/stock/adjust'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/stock/alerts.vue': {
      routes:
        | '/stock/alerts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/stock/in.vue': {
      routes:
        | '/stock/in'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/stock/movements.vue': {
      routes:
        | '/stock/movements'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/stock/out.vue': {
      routes:
        | '/stock/out'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/suppliers/index.vue': {
      routes:
        | '/suppliers/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/users/index.vue': {
      routes:
        | '/users/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/vehicles/compatibility.vue': {
      routes:
        | '/vehicles/compatibility'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
